server:
  port: 8088
  servlet:
    context-path: /code-gen

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.4:3316/devops_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: bocloud
    password: 123$abc
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      pool-name: dzgPool
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
